### ISSUE TITLE
Slava: Thoughts on Any-db?

### ISSUE THREAD

**Issue by ccorcos** [Slava/meteor-rethinkdb#22]
Hey Slava, I just built a package [`ccorcos:any-db`](https://github.com/ccorcos/meteor-any-db) and I'm curious your thoughts. It butchers Meteor principle 3 ("Database Everywhere") but I think it works nicely.

I just [started on rethinkdb as well](https://crater.io/posts/XmDZypBfhaHhG8PA6) but I'm running into some limitations with the change feed api.

**Comment by rclai** [comment]
It is not a good time to try to integrate RethinkDB into Meteor yet because they lack certain features in their changefeed like revision logs (which is really important, he says) among other things, as you have encountered. For more details, check out the talk he gave on last month's (was it last month?) devshop about "What it means to be a realtime database" or something like that.

I tried adding more stuff to his `simple:rethink` package [here](https://github.com/Profab/meteor-rethinkdb), which for the most part works in publishing more kinds of things, but it's still hacky. And here was my [PR](https://github.com/Slava/meteor-rethinkdb/pull/20), with his comments.

**Comment by ccorcos** [comment]
Yeah. That looks unhealthy. I think we're just ahead of the curve here honestly. 

At some point the reactivity will be the burden of the database, not the server. Until then, we'll just have to do it ourselves...

**Comment by rclai** [comment]
Yeah so looks like it may be better to start with SQL first.

**Comment by ccorcos** [comment]
Yeah, @numtel has that live-select thing going which looks cool.

I'm more than happy to build the driver, but what kills is getting it installed, starting and stopping it, and connecting to it from Node.
